zck.h: fix build on musl
The ssize_t type requires the <sys/types.h> header. This fixes build with musl
libc:

include/zck.h:68:1: error: unknown type name 'ssize_t'; did you mean 'size_t'?
   68 | ssize_t zck_read(zckCtx *zck, char *dst, size_t dst_size)
      | ^~~~~~~
      | size_t
include/zck.h:81:1: error: unknown type name 'ssize_t'; did you mean 'size_t'?
   81 | ssize_t zck_write(zckCtx *zck, const char *src, const size_t src_size)
      | ^~~~~~~
      | size_t

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>